title: "Lloyd De Osio"
author: "Lloyd De Osio"
description: "My Blogs"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

theme: minima  # Explicitly set Minima for GitHub Pages

# Minima settings
minima:
  skin: classic  # Or 'dark'/'border' for styles
  show_excerpts: true
  social_links:
    - { platform: email, user: lpdeosio@gmail.com }

plugins:
  - jekyll-feed
