title: "Lloyd De Osio"
author: "Lloyd De Osio"
description: "My Blogs"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Minima-specific layout settings
minima:
  show_excerpts: true
  date_format: "%B %d, %Y"

# Basic navigation (we'll add via includes later)
# external links
minima:
  social_links:
    - { platform: email, user: lpdeosio@gmail.com }

plugins:
  - jekyll-feed
